=begin
#Bugmark API

#all calls require BASIC AUTH

OpenAPI spec version: 0.0.1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.3.0

=end

require "uri"

module BmxApiRuby
  class IssuesApi
    attr_accessor :api_client

    def initialize(api_client = ApiClient.default)
      @api_client = api_client
    end

    # List all issues
    # List all issues
    # @param [Hash] opts the optional parameters
    # @return [Array<IssueOverview>]
    def get_issues(opts = {})
      data, _status_code, _headers = get_issues_with_http_info(opts)
      return data
    end

    # List all issues
    # List all issues
    # @param [Hash] opts the optional parameters
    # @return [Array<(Array<IssueOverview>, Fixnum, Hash)>] Array<IssueOverview> data, response status code and response headers
    def get_issues_with_http_info(opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug "Calling API: IssuesApi.get_issues ..."
      end
      # resource path
      local_var_path = "/issues"

      # query parameters
      query_params = {}

      # header parameters
      header_params = {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json'])

      # form parameters
      form_params = {}

      # http body (model)
      post_body = nil
      auth_names = []
      data, status_code, headers = @api_client.call_api(:GET, local_var_path,
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => 'Array<IssueOverview>')
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: IssuesApi#get_issues\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # Show issue detail
    # Show issue detail
    # @param issue_uuid issue uuid
    # @param [Hash] opts the optional parameters
    # @return [IssueDetail]
    def get_issues_issue_uuid(issue_uuid, opts = {})
      data, _status_code, _headers = get_issues_issue_uuid_with_http_info(issue_uuid, opts)
      return data
    end

    # Show issue detail
    # Show issue detail
    # @param issue_uuid issue uuid
    # @param [Hash] opts the optional parameters
    # @return [Array<(IssueDetail, Fixnum, Hash)>] IssueDetail data, response status code and response headers
    def get_issues_issue_uuid_with_http_info(issue_uuid, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug "Calling API: IssuesApi.get_issues_issue_uuid ..."
      end
      # verify the required parameter 'issue_uuid' is set
      if @api_client.config.client_side_validation && issue_uuid.nil?
        fail ArgumentError, "Missing the required parameter 'issue_uuid' when calling IssuesApi.get_issues_issue_uuid"
      end
      # resource path
      local_var_path = "/issues/{issue_uuid}".sub('{' + 'issue_uuid' + '}', issue_uuid.to_s)

      # query parameters
      query_params = {}

      # header parameters
      header_params = {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json'])

      # form parameters
      form_params = {}

      # http body (model)
      post_body = nil
      auth_names = []
      data, status_code, headers = @api_client.call_api(:GET, local_var_path,
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => 'IssueDetail')
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: IssuesApi#get_issues_issue_uuid\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end
  end
end
