=begin
#Bugmark API

#all calls require BASIC AUTH

OpenAPI spec version: 0.0.1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.3.0

=end

require "uri"

module BmxApiRuby
  class PositionsApi
    attr_accessor :api_client

    def initialize(api_client = ApiClient.default)
      @api_client = api_client
    end

    # List all positions
    # List all positions
    # @param [Hash] opts the optional parameters
    # @return [Array<PositionIds>]
    def get_positions(opts = {})
      data, _status_code, _headers = get_positions_with_http_info(opts)
      return data
    end

    # List all positions
    # List all positions
    # @param [Hash] opts the optional parameters
    # @return [Array<(Array<PositionIds>, Fixnum, Hash)>] Array<PositionIds> data, response status code and response headers
    def get_positions_with_http_info(opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug "Calling API: PositionsApi.get_positions ..."
      end
      # resource path
      local_var_path = "/positions"

      # query parameters
      query_params = {}

      # header parameters
      header_params = {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json'])

      # form parameters
      form_params = {}

      # http body (model)
      post_body = nil
      auth_names = ['base']
      data, status_code, headers = @api_client.call_api(:GET, local_var_path,
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => 'Array<PositionIds>')
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: PositionsApi#get_positions\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # Show position detail
    # Show position detail
    # @param uuid 
    # @param [Hash] opts the optional parameters
    # @return [PositionDetail]
    def get_positions_uuid(uuid, opts = {})
      data, _status_code, _headers = get_positions_uuid_with_http_info(uuid, opts)
      return data
    end

    # Show position detail
    # Show position detail
    # @param uuid 
    # @param [Hash] opts the optional parameters
    # @return [Array<(PositionDetail, Fixnum, Hash)>] PositionDetail data, response status code and response headers
    def get_positions_uuid_with_http_info(uuid, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug "Calling API: PositionsApi.get_positions_uuid ..."
      end
      # verify the required parameter 'uuid' is set
      if @api_client.config.client_side_validation && uuid.nil?
        fail ArgumentError, "Missing the required parameter 'uuid' when calling PositionsApi.get_positions_uuid"
      end
      # resource path
      local_var_path = "/positions/{uuid}".sub('{' + 'uuid' + '}', uuid.to_s)

      # query parameters
      query_params = {}

      # header parameters
      header_params = {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json'])

      # form parameters
      form_params = {}

      # http body (model)
      post_body = nil
      auth_names = ['base']
      data, status_code, headers = @api_client.call_api(:GET, local_var_path,
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => 'PositionDetail')
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: PositionsApi#get_positions_uuid\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end
  end
end
