=begin
#Bugmark API

#all calls require BASIC AUTH

OpenAPI spec version: 0.0.1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.3.0

=end

require 'spec_helper'
require 'json'

# Unit tests for BmxApiRuby::IssuesApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'IssuesApi' do
  before do
    # run before each test
    @instance = BmxApiRuby::IssuesApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of IssuesApi' do
    it 'should create an instance of IssuesApi' do
      expect(@instance).to be_instance_of(BmxApiRuby::IssuesApi)
    end
  end

  # unit tests for get_issues
  # List all issues
  # List all issues
  # @param [Hash] opts the optional parameters
  # @return [Array<IssueOverview>]
  describe 'get_issues test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_issues_issue_uuid
  # Show issue detail
  # Show issue detail
  # @param issue_uuid issue uuid
  # @param [Hash] opts the optional parameters
  # @return [IssueDetail]
  describe 'get_issues_issue_uuid test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
