=begin
#Bugmark API

#all calls require BASIC AUTH

OpenAPI spec version: 0.0.1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.3.0

=end

require 'spec_helper'
require 'json'

# Unit tests for BmxApiRuby::OffersApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'OffersApi' do
  before do
    # run before each test
    @instance = BmxApiRuby::OffersApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of OffersApi' do
    it 'should create an instance of OffersApi' do
      expect(@instance).to be_instance_of(BmxApiRuby::OffersApi)
    end
  end

  # unit tests for get_offers
  # List all offers
  # List all offers
  # @param [Hash] opts the optional parameters
  # @return [Array<OfferOverview>]
  describe 'get_offers test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_offers_uuid
  # Show offer detail
  # Show offer detail
  # @param uuid 
  # @param [Hash] opts the optional parameters
  # @return [OfferDetail]
  describe 'get_offers_uuid test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for post_offers_buy
  # Create a buy offer
  # Create a buy offer
  # @param side TBD
  # @param volume TBD
  # @param price TBD
  # @param issue TBD
  # @param maturation TBD
  # @param expiration TBD
  # @param [Hash] opts the optional parameters
  # @option opts [BOOLEAN] :aon TBD
  # @return [Status]
  describe 'post_offers_buy test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
