=begin
#Bugmark API

#all calls require BASIC AUTH

OpenAPI spec version: 0.0.1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.3.0

=end

require 'spec_helper'
require 'json'

# Unit tests for BmxApiRuby::TimeApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'TimeApi' do
  before do
    # run before each test
    @instance = BmxApiRuby::TimeApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of TimeApi' do
    it 'should create an instance of TimeApi' do
      expect(@instance).to be_instance_of(BmxApiRuby::TimeApi)
    end
  end

  # unit tests for get_time_future_week_ends
  # future week-ends
  # future week-ends
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :count count (default 4)
  # @return [Array<TimeWeekEnds>]
  describe 'get_time_future_week_ends test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_time_now
  # current exchange time
  # current exchange time
  # @param [Hash] opts the optional parameters
  # @return [TimeNow]
  describe 'get_time_now test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_time_rebuild_date
  # system rebuild real-time
  # system rebuild real-time
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'get_time_rebuild_date test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for put_time_increment_day_offset
  # increment day offset
  # increment day offset
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :count count (default 1)
  # @return [Status]
  describe 'put_time_increment_day_offset test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
