=begin
#Bugmark API

#all calls require BASIC AUTH

OpenAPI spec version: 0.0.1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.3.0

=end

require 'spec_helper'
require 'json'

# Unit tests for BmxApiRuby::TrackersApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'TrackersApi' do
  before do
    # run before each test
    @instance = BmxApiRuby::TrackersApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of TrackersApi' do
    it 'should create an instance of TrackersApi' do
      expect(@instance).to be_instance_of(BmxApiRuby::TrackersApi)
    end
  end

  # unit tests for get_trackers
  # List all tracker ids
  # List all tracker ids
  # @param [Hash] opts the optional parameters
  # @return [Array<TrackerIds>]
  describe 'get_trackers test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_trackers_detail
  # List all tracker details
  # List all tracker details
  # @param [Hash] opts the optional parameters
  # @return [Array<TrackerDetail>]
  describe 'get_trackers_detail test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_trackers_uuid
  # Show detail for one tracker
  # Show detail for one tracker
  # @param uuid tracker UUID
  # @param [Hash] opts the optional parameters
  # @option opts [BOOLEAN] :issues include issues
  # @return [TrackerDetail]
  describe 'get_trackers_uuid test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for post_trackers
  # Create a tracker
  # Create a GitHub tracker. 
  # @param type tracker type
  # @param name tracker name
  # @param [Hash] opts the optional parameters
  # @option opts [BOOLEAN] :ghsync GH sync on create
  # @return [TrackerIds]
  describe 'post_trackers test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for put_trackers
  # Sync a tracker
  # Sync a GitHub tracker. 
  # @param uuid tracker uuid
  # @param [Hash] opts the optional parameters
  # @return [Status]
  describe 'put_trackers test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
