=begin
#Bugmark API

#all calls require BASIC AUTH

OpenAPI spec version: 0.0.1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.3.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for BmxApiRuby::NextWeekEnds
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'NextWeekEnds' do
  before do
    # run before each test
    @instance = BmxApiRuby::NextWeekEnds.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of NextWeekEnds' do
    it 'should create an instance of NextWeekEnds' do
      expect(@instance).to be_instance_of(BmxApiRuby::NextWeekEnds)
    end
  end
  describe 'test attribute "next_week_ends"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end

