=begin
#Bugmark API

#all calls require BASIC AUTH

OpenAPI spec version: 0.0.1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.3.0

=end

require 'date'

module BmxApiRuby
  # Show host object counts: number of users, offers, contracts, etc. 
  class HostCount
    # Bugmark Hostname
    attr_accessor :host_name

    # Number of Users
    attr_accessor :users

    # Number of Repos
    attr_accessor :repos

    # Number of Issues
    attr_accessor :issues

    # Number of Offers
    attr_accessor :offers

    # Number of Open Offers
    attr_accessor :offers_open

    # Number of Open Offers to Buy Fixed
    attr_accessor :offers_open_bf

    # Number of Open Offers to Buy Unfixed
    attr_accessor :offers_open_bu

    # Number of Contracts
    attr_accessor :contracts

    # Number of Open Contracts
    attr_accessor :contracts_open

    # Number of Positions
    attr_accessor :positions

    # Number of Amendments
    attr_accessor :amendments

    # Number of Escrows
    attr_accessor :escrows

    # Number of Events
    attr_accessor :events


    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'host_name' => :'host_name',
        :'users' => :'users',
        :'repos' => :'repos',
        :'issues' => :'issues',
        :'offers' => :'offers',
        :'offers_open' => :'offers_open',
        :'offers_open_bf' => :'offers_open_bf',
        :'offers_open_bu' => :'offers_open_bu',
        :'contracts' => :'contracts',
        :'contracts_open' => :'contracts_open',
        :'positions' => :'positions',
        :'amendments' => :'amendments',
        :'escrows' => :'escrows',
        :'events' => :'events'
      }
    end

    # Attribute type mapping.
    def self.swagger_types
      {
        :'host_name' => :'String',
        :'users' => :'Integer',
        :'repos' => :'Integer',
        :'issues' => :'Integer',
        :'offers' => :'Integer',
        :'offers_open' => :'Integer',
        :'offers_open_bf' => :'Integer',
        :'offers_open_bu' => :'Integer',
        :'contracts' => :'Integer',
        :'contracts_open' => :'Integer',
        :'positions' => :'Integer',
        :'amendments' => :'Integer',
        :'escrows' => :'Integer',
        :'events' => :'Integer'
      }
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      return unless attributes.is_a?(Hash)

      # convert string to symbol for hash key
      attributes = attributes.each_with_object({}){|(k,v), h| h[k.to_sym] = v}

      if attributes.has_key?(:'host_name')
        self.host_name = attributes[:'host_name']
      end

      if attributes.has_key?(:'users')
        self.users = attributes[:'users']
      end

      if attributes.has_key?(:'repos')
        self.repos = attributes[:'repos']
      end

      if attributes.has_key?(:'issues')
        self.issues = attributes[:'issues']
      end

      if attributes.has_key?(:'offers')
        self.offers = attributes[:'offers']
      end

      if attributes.has_key?(:'offers_open')
        self.offers_open = attributes[:'offers_open']
      end

      if attributes.has_key?(:'offers_open_bf')
        self.offers_open_bf = attributes[:'offers_open_bf']
      end

      if attributes.has_key?(:'offers_open_bu')
        self.offers_open_bu = attributes[:'offers_open_bu']
      end

      if attributes.has_key?(:'contracts')
        self.contracts = attributes[:'contracts']
      end

      if attributes.has_key?(:'contracts_open')
        self.contracts_open = attributes[:'contracts_open']
      end

      if attributes.has_key?(:'positions')
        self.positions = attributes[:'positions']
      end

      if attributes.has_key?(:'amendments')
        self.amendments = attributes[:'amendments']
      end

      if attributes.has_key?(:'escrows')
        self.escrows = attributes[:'escrows']
      end

      if attributes.has_key?(:'events')
        self.events = attributes[:'events']
      end

    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      invalid_properties = Array.new
      return invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      return true
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          host_name == o.host_name &&
          users == o.users &&
          repos == o.repos &&
          issues == o.issues &&
          offers == o.offers &&
          offers_open == o.offers_open &&
          offers_open_bf == o.offers_open_bf &&
          offers_open_bu == o.offers_open_bu &&
          contracts == o.contracts &&
          contracts_open == o.contracts_open &&
          positions == o.positions &&
          amendments == o.amendments &&
          escrows == o.escrows &&
          events == o.events
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Fixnum] Hash code
    def hash
      [host_name, users, repos, issues, offers, offers_open, offers_open_bf, offers_open_bu, contracts, contracts_open, positions, amendments, escrows, events].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      self.class.swagger_types.each_pair do |key, type|
        if type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the the attribute
          # is documented as an array but the input is not
          if attributes[self.class.attribute_map[key]].is_a?(Array)
            self.send("#{key}=", attributes[self.class.attribute_map[key]].map{ |v| _deserialize($1, v) } )
          end
        elsif !attributes[self.class.attribute_map[key]].nil?
          self.send("#{key}=", _deserialize(type, attributes[self.class.attribute_map[key]]))
        end # or else data not found in attributes(hash), not an issue as the data can be optional
      end

      self
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def _deserialize(type, value)
      case type.to_sym
      when :DateTime
        DateTime.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :BOOLEAN
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        temp_model = BmxApiRuby.const_get(type).new
        temp_model.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        next if value.nil?
        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map{ |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end

end
